builds:
- id: sems_mitm_exporter
  binary: sems_mitm_exporter
  main: ./cmd/sems_mitm_exporter
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
