version: 2
builds:
- id: sems_mitm_exporter
  binary: sems_mitm_exporter
  main: ./cmd/sems_mitm_exporter
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  - arm64

changelog:
  use: github-native

dockers:
- ids:
  - sems_mitm_exporter
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-amd64"
  use: buildx
  build_flag_templates:
  - "--build-arg=BINARY=sems_mitm_exporter"
  - "--platform=linux/amd64"
- ids:
  - sems_mitm_exporter
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--build-arg=BINARY=sems_mitm_exporter"
  - "--platform=linux/arm64/v8"

docker_manifests:
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-arm64v8"
- name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:latest"
  image_templates:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-amd64"
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/sems_mitm_exporter:v{{ .Version }}-arm64v8"

release:
  extra_files:
  - glob: "{{ .Env.GITHUB_SBOM_PATH }}"
    name_template: "{{ .ProjectName }}.v{{ .Version }}.sbom.spdx.json"
