name: coverage
on:
  push:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: stable
    - name: Calculate coverage
      run: |
        go test -v -covermode=atomic -coverprofile=cover.out.raw -coverpkg=./... ./...
        # remove mocks from coverage calculation
        grep -Ev 'mock_|_enumer.go' cover.out.raw > cover.out
    - name: Generage coverage badge
      uses: vladopajic/go-test-coverage@1079cd4e58dda229c04ffdb6324fc3756b8542ff # v2.10.1
      with:
        profile: cover.out
        local-prefix: github.com/smlx/goodwe-exporters
        git-token: ${{ secrets.GITHUB_TOKEN }}
        # orphan branch for storing badges
        git-branch: badges
