name: coverage
on:
  push:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: stable
    - name: Calculate coverage
      run: |
        go test -v -covermode=atomic -coverprofile=cover.out.raw -coverpkg=./... ./...
        # remove mocks from coverage calculation
        grep -Ev 'mock_|_enumer.go' cover.out.raw > cover.out
    - name: Generage coverage badge
      uses: vladopajic/go-test-coverage@1079cd4e58dda229c04ffdb6324fc3756b8542ff # v2.10.1
      with:
        profile: cover.out
        local-prefix: github.com/smlx/goodwe-exporters
        git-token: ${{ secrets.GITHUB_TOKEN }}
        # orphan branch for storing badges
        git-branch: badges
