name: Lint
on: pull_request
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=180s
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: .github/commitlint.config.js
