name: test
on:
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  test-go:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: stable
    - run: go test -v ./...
