name: Test
on: pull_request
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Run Tests
      run: go test -v ./...
