name: test
on:
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  test-go:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: stable
    - run: go test -v ./...
